### ISSUE TITLE
Dialogue to select Folders doesn't accept "OK" unless folder name is typed

### ISSUE THREAD

**Issue by Termuellinator** [the-sane/lug-helper#10]
I just tried to force the helper to create new .config files and noticed that i can't complete the selection by clicking.
You **have to** write the subfolder of the current view in the "Name" field before you can click "OK"

I haven't found any bugreports in that regards (although that might be because of the ongoing transition from bugzilla to gitlab?), but it might of course be only an issue on KDE.

Even if it is only present in KDE i think we should maybe give a hint about this in a dialoge? If it's only on KDE then maybe with a check if the current DE is KDE, if that is easily done somehow?

**Comment by the-sane** [comment]
:thinking: So, you're saying when you're at the screen where it asks you to "Select your Star Citizen WINE prefix directory" and you click on the directory then click OK, it doesn't do anything?  Or does it throw an error?

I just tried that under Gnome and it works fine.  What if you double click into the folder and then click OK?

**Comment by Termuellinator** [comment]
no error, neither in GUI nor terminaloutput.
And nope, no doubleclick, no only select and then press enter and nothing else i could think of ^^

**Comment by the-sane** [comment]
Mactan and TinybuttMike also have KDE and weren't able to reproduce this.  No idea what could be going on :shrug:

**Comment by Termuellinator** [comment]
ok, as long as its just some strange quirk on my system i'm relieved ^^

**Comment by the-sane** [comment]
Just checking in, have you figured out why this was happening to you?

**Comment by Termuellinator** [comment]
nope, tbh i haven't worried about it too much, as noone else with KDE or manjaro can reproduce it - i guess we can close this issue?
