### ISSUE TITLE
no `--help` output

### ISSUE THREAD

**Issue by victort** [the-sane/lug-helper#12]
just launches into the script.

(yeah, i know there isn't any command line options(, yet?) but it will confuse greybeards.)

**Comment by the-sane** [comment]
Wouldn’t want those graybeards to be confused!  That’s a good idea and can be added easily enough. If you get some time, writing the help/usage message that should show up would be extremely helpful.

I try to format everything for a standard 80 character wide terminal window.

**Comment by victort** [comment]
Yes™

**Comment by the-sane** [comment]
Merged https://github.com/the-sane/lug-helper/pull/13
