### ISSUE TITLE
"wine-sc-lug" runner is listed as "/dev/null"

### ISSUE THREAD

**Issue by emilwojcik93** [the-sane/lug-helper#19]
Hello,
there is a wrongly named runner in script:
https://github.com/the-sane/lug-helper/blob/e0d149494d63bf1b657be56cdefecf5b0fed39b7/lug-helper.sh#L109

"/dev/null" should be change to "wine-sc-lug"

Best regards,
emilwojcik93

**Comment by the-sane** [comment]
Hi!

`/dev/null` is referring to the person in the LUG who maintains that particular runner.  That’s the name he uses in Spectrum and in the ‘verse. We name it that way so it’s easier for everyone to identify when we tell someone, for example, “try using dev/null’s runner”.

Thanks for keeping an eye on things though! Much appreciated!
