### ISSUE TITLE
Live work fine but ptu give wine crash after small  splash screen

### ISSUE THREAD

**Issue by w35134** [the-sane/lug-helper#21]
i instaled the game with lutris and the live client work fine, but when i try to open the ptu it show the little blue splash screen and take more time than the live, so it closes and open a error report windows for wine, after close the wine report it come back to launcher asking for verify files, i did try with several runers that i instaled from lug-helper best one for live is 6.10 gold fsync runner but also crash on ptu 3.14, here is the output:
[15:40:59.246] [info] Launching Star Citizen PTU from (C:\Program Files\Roberts Space Industries\StarCitizen\PTU)
[15:41:37.300] [error] Star Citizen process exited abnormally (code: 732823384) : Command failed: C:\Program Files\Roberts Space Industries\StarCitizen\PTU\Bin64\StarCitizen.exe -no_login_dialog -no_login_dialog

**Comment by Termuellinator** [comment]
Hi there - this repo is mainly for issues around the helper itself. From what i've heard 6.6 gold fsync from molotov should work pretty reliably with 3.14 PTU. If that doesn't help, it might be best to check by our spectrum channel - i'm currently a bit behind on whats going on tbh ^^
Spectrum Channel: https://robertsspaceindustries.com/spectrum/community/LUG/lobby/104 or the discord server: https://discord.gg/npea8cEzyp
